### ISSUE TITLE
💥 rename this repo

### ISSUE THREAD

**Issue by jdhoffa** [r-staceans/blazr#4]
A `multiverse` package is [already on CRAN](https://github.com/MUCollective/multiverse) (and seems active), so we may want to start thinking about a new package name

**Comment by jdhoffa** [comment]
Maybe `threadr`

**Comment by jdhoffa** [comment]
> Damn. Maybe omniverse, rustyverse, hyperverse, blazar, quasar...Trying to keep the them of space qnd speed. Blazar is non existent. There are some similar to quasar. In the 'plyr' theme: rusplyr, fplyr or something like that.

_Originally posted by @jibarozzo in https://github.com/r-staceans/.github/discussions/1#discussioncomment-11491827_

**Comment by jdhoffa** [comment]
I think the important outcome of the package is "speeding up `dplyr` using multi-threading" (the fact that it uses Rust is an artifact of that outcome, but not crucially important for users to be aware of, so I don't think it needs to be in the name)

In that spirit, I think my two top contenders would be:
`blazar` (speed)
and `threadr` (multi-threading)

**Comment by jdhoffa** [comment]
One (incredibly NIT) comment:
Quasars are objects that emit ultra-relativistic pulses in an incredibly precise way. 

To me the name evokes something more related to a clock rate/ timer/ something to do with precise benchmarking or something like that. Not that related to multithreading

(I used to study astrophysics lol so I might just be overly aware of this)

**Comment by jibarozzo** [comment]
1 vote for `threadr`

**Comment by DrEntropy** [comment]
Is the goal is to specifically speed up data operations like in dplyr  ?

**Comment by jdhoffa** [comment]
I think the goal is still not well-defined 😊

One of _my_ goals is to explore multi-threading in Rust and see if there is a safe way to offer an interface for that in R. 
An application of the above–that might have broad public appeal–is some wrapper around common `dplyr` or data operations that pass those data and operations to Rust. 

Given that we are likely not going to be able to compete with [polars](https://pola.rs/) in terms of speed, one option could be to recode certain `dplyr` functions with identical names/ APIs etc., so allow for a plug-and-play replacement

**Comment by jdhoffa** [comment]
Very open to suggestions here!

As I'm writing this out, it feels like a simple (safe) multi-threading API that can be called from R is probably a lower lift then writing a full parallelized data processing package, but I'm game for either (or both) still 😃

**Comment by jibarozzo** [comment]
I align with the goal of exploring multi-threading in Rust-R. Speed and safety is what drove me to learn it.  I'm good with either, I think keeping it simple would be be the way to go since the ultimate goal is to learn how to write Rust for R. For me it's a lot of new things so it's exciting either way.

**Comment by DrEntropy** [comment]
OK i was just thinking if we had something more specific in mind the name might be more narrowly focused too.  But something like threadr could be a placeholder.  
PS: Threadr also exists (https://github.com/skgrange/threadr)  .     Maybe `crankr` ?  `asyncR` ?   

As for specific things to consider, how about something small like generating bootstrap samples in parallel?  (I mean this can be done already using the `parallel` package but this would be more turnkey).  This could be expanded later to include more general data sampling.   `multidrawr`  ?

I don't think we have the bandwidth to recreate a general purpose library like `parallel` but that could be a long term goal.

**Comment by jdhoffa** [comment]
My gut feeling is to not bikeshed on the name too much, and to just start experimenting with functionality. 

I think none of us have sufficient experience yet to super precisely define what we can/ can't achieve with this package, so as long as the name broadly represents our goals that's fine

Maybe in a few months we will have a more precise idea of our goals and we can pick the discussion back up then

**Comment by jdhoffa** [comment]
All that to say: my vote is for threadr 

And let's direct our energy toward the more difficult work.

In 3 months we can see what we've been able to build, and consider renaming at that point if necessary

**Comment by asbates** [comment]
> I think the goal is still not well-defined 😊

That's what makes it so exciting!

> One of _my_ goals is to explore multi-threading in Rust and see if there is a safe way to offer an interface for that in R. An application of the above–that might have broad public appeal–is some wrapper around common `dplyr` or data operations that pass those data and operations to Rust.
> 
> Given that we are likely not going to be able to compete with [polars](https://pola.rs/) in terms of speed, one option could be to recode certain `dplyr` functions with identical names/ APIs etc., to allow for a plug-and-play replacement

I think for now let's stick to the idea of wrapping a handful of `dplyr` functions and see where it goes. Who knows, maybe it could end up being a backend for `dplyr` like `dtplyr`. Or maybe we abandon the idea in a month. As long as we're learning something we're doing everything right.
